### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Panda0907** [irskid5/drr_restaurants#1]
Hello author, I am a student, can you send me the dataset you used?Thanks!
My E-mail address：huali_pan@163.com

**Comment by Veslie-z** [comment]
> Hello author, I am a student, can you send me the dataset you used?Thanks! My E-mail address：[huali_pan@163.com](mailto:huali_pan@163.com)

Hello, have you got the data set?

**Comment by irskid5** [comment]
Hey everyone, the dataset we used was the Yelp dataset. There is a reference in the README to the dataset.

**Comment by Veslie-z** [comment]
I know, but you didn't provide the processed data, because I read your data.py is like this, you don't seem to provide the dataset folder, thank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "irskid5/drr_restaurants"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 凌晨1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [irskid5/drr_restaurants] Dataset (Issue #1)





 
Hey everyone, the dataset we used was the Yelp dataset. There is a reference in the README to the dataset.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by irskid5** [comment]
See https://github.com/irskid5/drr_restaurants/issues/2#issuecomment-1143390536
